---
- name: install ddns package
  opkg: name=ddns-scripts state=present update_cache=yes

- name: install ddns package
  opkg: name={{item}} state=present update_cache=yes
  with_items: "{{packages}}"

- name: set ddns-services
  include: set_ddns_service.yml
  vars:
    name: "{{item.name}}"
    domain: "{{item.domain}}"
    username: "{{item.username}}"
    password: "{{item.password}}"
    interface: "{{item.interface | default('wan')}}"
    enabled: "{{item.enabled | default(True)}}"
    ip_source: "{{item.ip_source | default({})}}"
    ip_url: "{{item.ip_url | default({})}}"
  with_items: "{{ddns_services}}"
