---
- name: install ddns package
  opkg: name=ddns-scripts state=present update_cache=yes

- name: install ddns package
  opkg: name={{item}} state=present update_cache=yes
  with_items: "{{packages}}"

- name: set ddns-services
  uci:
    command: set_object
    config: ddns
    type: service
    section: "{{item.name}}"
    values:
      service_name: "{{item.name}}"
      domain: "{{item.domain}}"
      username: "{{item.username}}"
      password: "{{item.password}}"
      interface: "{{item.interface | default('wan')}}"
      enabled: "{{item.enabled | default(True) | int}}"
      ip_source: "{{item.ip_source | default({})}}"
      ip_url: "{{item.ip_url | default({})}}"
  with_items: "{{ddns_services}}"
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns
