---
- name: set ddns_service service_name
  uci:
    command: set
    config: "ddns"
    section: "{{name}}"
    option: "service_name"
    type: "service"
    value: "{{name}}"
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns

- name: set ddns_service domain
  uci:
    command: set
    config: "ddns"
    section: "{{name}}"
    option: "domain"
    type: "service"
    value: "{{domain}}"
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns

- name: set ddns_service username
  uci:
    command: set
    config: "ddns"
    section: "{{name}}"
    option: "username"
    type: "service"
    value: "{{username}}"
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns

- name: set ddns_service password
  uci:
    command: set
    config: "ddns"
    section: "{{name}}"
    option: "password"
    type: "service"
    value: "{{password}}"
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns

- name: set ddns_service interface
  uci:
    command: set
    config: "ddns"
    section: "{{name}}"
    option: "interface"
    type: "service"
    value: "{{interface}}"
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns

- name: set ddns_service enabled
  uci:
    command: set
    config: "ddns"
    section: "{{name}}"
    option: "enabled"
    type: "service"
    value: "{{enabled | int}}"
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns

- name: set ddns_service ip_source
  uci:
    command: set
    config: "ddns"
    section: "{{name}}"
    option: "ip_source"
    type: "service"
    value: "{{ip_source}}"
  when: ip_source != {}
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns

- name: set ddns_service ip_url
  uci:
    command: set
    config: "ddns"
    section: "{{name}}"
    option: "ip_url"
    type: "service"
    value: "{{ip_url}}"
  when: ip_url != {}
  notify:
    - uci commit ddns
    - reload ddns-scripts for openwrt-ddns
